version: "3.8"

services:
  backend:
    build: ./backend
    container_name: mern-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/mern_task_app
    depends_on:
      - mongo
    networks:
      - mern-net

  frontend:
    build: ./frontend
    container_name: mern-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - mern-net

  mongo:
    image: mongo:6.0
    container_name: mern-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-net

volumes:
  mongo-data:

networks:
  mern-net:
    driver: bridge
